"""catalog tables

Revision ID: 4b72ceb2e512
Revises: 4b6888f72463
Create Date: 2026-06-12 10:08:43.735415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b72ceb2e512'
down_revision: Union[str, Sequence[str], None] = '4b6888f72463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('column_mapping_template', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('catalog_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('article', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'article', 'name')
    )
    op.create_index(op.f('ix_catalog_items_article'), 'catalog_items', ['article'], unique=False)
    op.create_index(op.f('ix_catalog_items_name'), 'catalog_items', ['name'], unique=False)
    op.create_index(op.f('ix_catalog_items_supplier_id'), 'catalog_items', ['supplier_id'], unique=False)
    op.create_table('price_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'version')
    )
    op.create_index(op.f('ix_price_lists_supplier_id'), 'price_lists', ['supplier_id'], unique=False)
    op.create_table('item_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('price_list_id', sa.Integer(), nullable=False),
    sa.Column('price_level_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['catalog_items.id'], ),
    sa.ForeignKeyConstraint(['price_level_id'], ['price_levels.id'], ),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'price_list_id', 'price_level_id')
    )
    op.create_index(op.f('ix_item_prices_item_id'), 'item_prices', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_prices_price_list_id'), 'item_prices', ['price_list_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_prices_price_list_id'), table_name='item_prices')
    op.drop_index(op.f('ix_item_prices_item_id'), table_name='item_prices')
    op.drop_table('item_prices')
    op.drop_index(op.f('ix_price_lists_supplier_id'), table_name='price_lists')
    op.drop_table('price_lists')
    op.drop_index(op.f('ix_catalog_items_supplier_id'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_name'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_article'), table_name='catalog_items')
    op.drop_table('catalog_items')
    op.drop_table('suppliers')
    op.drop_table('price_levels')
    # ### end Alembic commands ###
